# Generated by Django 2.1.7 on 2019-03-19 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('type', models.CharField(choices=[('D', 'DEV'), ('P', 'PROD')], max_length=1)),
                ('currentState', models.CharField(blank=True, choices=[('W', 'WORKING'), ('SP', 'STOPPED'), ('SR', 'STARTED'), ('F', 'FAILED')], max_length=2)),
                ('link', models.URLField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('version', models.CharField(max_length=16)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('modifiedAt', models.DateTimeField(blank=True, null=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.Bot')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('I', 'INFO'), ('W', 'WARNING'), ('E', 'ERROR'), ('S', 'SUCCESS')], max_length=1)),
                ('createdAt', models.DateTimeField()),
                ('message', models.TextField()),
                ('bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.Bot')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.AlterOrderWithRespectTo(
            name='code',
            order_with_respect_to='bot',
        ),
        migrations.AddIndex(
            model_name='bot',
            index=models.Index(fields=['name', 'createdAt'], name='bot_bot_name_bfd920_idx'),
        ),
    ]
