# Generated by Django 2.1.7 on 2019-03-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='code',
            order_with_respect_to=None,
        ),
        migrations.RemoveField(
            model_name='code',
            name='version',
        ),
    ]
